# Generated by Django 2.2.6 on 2019-10-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='usernames',
            field=models.TextField(default=''),
        ),
    ]
