# Generated by Django 2.2.6 on 2019-10-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20191025_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='usernames',
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='users',
            field=models.ManyToManyField(to='api_app.Student'),
        ),
    ]
